[[unit_test]]
    files = [
        "impv-sem.sem"
    ]
    
    [[unit_test.test]]
        program = "( $assign-c ($+ $x $y) )"
        
        examples = [
            {x0=0, y0=5, c0=0, c2=5},
            {x0=1, y0=1, c0=0, c2=2},
            {x0=5, y0=3, c0=0, c2=8}
        ]
        

    [[unit_test.test]]
        program = "( $cons ($assign-c $0) ($while ($lt $0 $x) ($cons ($assign-c ($+ $c $y)) ($assign-x ($+ $x ($- $1))))))"
        
        examples = [
            {x0=0, y0=5, c0=0, c2=0},
            {x0=1, y0=1, c0=0, c2=1},
            {x0=5, y0=10, c0=0, c2=50},
            {x0=10, y0=10, c0=0, c2=100}
        ]
        
