
[[task]]
    files = [
        "./add-xxy.sem",
        "./max-exp.sem",
        "./int-compare.sem",
    ]

    # temp field to set background theory
    lib = "lia"

    output_file_json = "simple-lia.out.json"
    log_file = "simple-lia.out.log"

    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            