
[[task]]
    files = [
        "./magic-regex-test-lin.sem",
        "./magic-regex-test-log.sem",
    ]

    # temp field to set background theory
    lib = "regex_bmat"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            