
[[task]]
    files = [
        "./GCPE_01.sem",
        "./GCPE_02.sem",
        # "./GCPE_03.sem",
        # "./GCPE_04.sem",
        # "./GCPE_05.sem",
        # "./GCPE_06.sem",
        # "./GCPE_07.sem",
        # "./GCPE_08.sem",
        # "./GCPE_09.sem",
        # "./GCPE_10.sem",
        # "./GCPE_11.sem",
        # "./GCPE_12.sem",
        # "./GCPE_13.sem",
        # "./GCPE_14.sem",
        # "./GCPE_15.sem",
        # "./GCPE_16.sem",
        # "./GCPE_17.sem",
        # "./GCPE_18.sem",
        # "./GCPE_19.sem",
        # "./GCPE_20.sem",
        # "./GCPE_21.sem",
        # "./GCPE_22.sem",
        # "./GCPE_23.sem",
        # "./GCPE_24.sem",
        # "./GCPE_25.sem",
    ]

    # temp field to set background theory
    lib = "lia" 

    output_file_json = "messy-regex.json"
    log_file = "messy-regex.log"

    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            
    [[task.solver]]
        method = "probe"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_limit_start = 12
            cost_limit_step = 3