
[[task]]
    files = [
        "./basicTest_MAX_01.sem",
        "./basicTest_MAX_02.sem",
        "./basicTest_MAX_03.sem",
        "./basicTest_AddOne_01.sem",
        "./basicTest_AddByWhileLoop_01.sem",
        "./basicTest_AddByWhileLoop_02.sem",
        "./basicTest_AddByWhileLoop_03.sem",
        "./basicTest_AddByWhileLoop_04.sem",
        "./basicTest_AddByWhileLoop_05.sem",
        "./basicTest_SumWithLimitedOps_01.sem",
        "./basicTest_SumWithLimitedOps_02.sem",
        "./basicTest_SumByWhileLoop_01.sem",
        "./basicTest_SetBothtoLarger_01.sem",
        "./basicTest_MultByWhileLoop_01.sem",
        "./basicTest_MultByWhileLoop_02.sem",
        "./basicTest_Fib_01.sem",
        "./basicTest_Sanity01.sem",
        "./minimal_unsat.sem",
        "./basicTest20_one_way_loop.sem",
        "./basicTest21_one_way_loop.sem",
    ]

    # temp field to set background theory
    lib = "lia"

    output_file_json = "basic_bv.out.json"
    log_file = "basic_bv.out.log"

    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            max_cost = 30