
[[task]]
    # basic_bv
    files = [
        "basic_bv/BVtest_ADD_01.sem",
        "basic_bv/BVtest_AND_01.sem",
        "basic_bv/BVtest_AND_02.sem",
        "basic_bv/BVtest_AND_03.sem",
        "basic_bv/BVtest_MAX_01.sem",
        "basic_bv/BVtest_NAND_01.sem",
        "basic_bv/BVtest_PLUS_01.sem",
        "basic_bv/BVtest_Swap_XOR_01.sem",
        "basic_bv/BVtest_Swap_XOR_02.sem",
        "basic_bv/BVtest_Swap_XOR_03.sem",
        "basic_bv/BVtest_While_01_XOR_by_AND_OR.sem",
        "basic_bv/BVtest_While_02_XOR_by_AND_OR_ADD.sem",
        "basic_bv/BVtest_XOR_01.sem",
        "basic_bv/BVtest_XOR_02.sem",
        "basic_bv/BVtest_XOR_03.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
