
[[task]]
    # basic_1
    files = [
        "basic_1/basicTest20_one_way_loop.sem",
        "basic_1/basicTest21_one_way_loop.sem",
        "basic_1/basicTest_AddByWhileLoop_01.sem",
        "basic_1/basicTest_AddByWhileLoop_02.sem",
        "basic_1/basicTest_AddByWhileLoop_03.sem",
        "basic_1/basicTest_AddByWhileLoop_04.sem",
        "basic_1/basicTest_AddByWhileLoop_05.sem",
        "basic_1/basicTest_AddOne_01.sem",
        "basic_1/basicTest_Fib_01.sem",
        "basic_1/basicTest_MAX_01.sem",
        "basic_1/basicTest_MAX_02.sem",
        "basic_1/basicTest_MAX_03.sem",
        "basic_1/basicTest_MultByWhileLoop_01.sem",
        "basic_1/basicTest_MultByWhileLoop_02.sem",
        "basic_1/basicTest_Sanity01.sem",
        "basic_1/basicTest_SetBothtoLarger_01.sem",
        "basic_1/basicTest_SumByWhileLoop_01.sem",
        "basic_1/basicTest_SumWithLimitedOps_01.sem",
        "basic_1/basicTest_SumWithLimitedOps_02.sem",
        "basic_1/minimal_unsat.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
