# Files for which MESSY reported SAT using any method
[[task]]
    files = [
        'basic_1/basicTest_AddOne_01.sem',
        'basic_1/basicTest_SumByWhileLoop_01.sem',
        'basic_1/basicTest_SumWithLimitedOps_01.sem',
        'basic_bv/BVtest_AND_03.sem',
        'basic_bv/BVtest_Swap_XOR_03.sem',
        'basic_bv/BVtest_XOR_02.sem',
        'SAS_01_factorialTests/no01_factorialTest_02.sem',
        'SAS_17_arraysumTest/no17_arraysum_01.sem',
        'SAS_17_arraysumTest/no17_arraysum_02.sem',
        'SAS_17_arraysumTest/no17_arraysum_04.sem',
        'SAS_17_arraysumTest/no17_arraysum_06.sem',
        'SAS_17_arraysumTest/no17_arraysum_07.sem',
        'SAS_17_arraysumTest/no17_arraysum_08.sem',
        'SAS_18_arrayprodTest/no18_arrayprod_01.sem',
        'SAS_18_arrayprodTest/no18_arrayprod_02.sem',
        'SAS_18_arrayprodTest/no18_arrayprod_03.sem',
        'SAS_18_arrayprodTest/no18_arrayprod_04.sem',
        'SAS_18_arrayprodTest/no18_arrayprod_06.sem',
        'SAS_18_arrayprodTest/no18_arrayprod_07.sem',
        'SAS_18_arrayprodTest/no18_arrayprod_08.sem',
        'SAS_23_maxTest/no23_max_01.sem',
        'SAS_23_maxTest/no23_max_02.sem',
        'SAS_23_maxTest/no23_max_06.sem',
        'SAS_24_minTest/no24_min_02.sem',
        'SAS_26_sumsquaresTest/no26_sumsquares_01.sem',
        'SAS_26_sumsquaresTest/no26_sumsquares_02.sem',
        'SAS_26_sumsquaresTest/no26_sumsquares_06.sem',
        'SAS_27_prodsquaresTest/no27_prodsquares_02.sem',
        'SAS_27_prodsquaresTest/no27_prodsquares_06.sem',
        'SAS_28_sumprodsTest/no28_sumprods_01.sem',
        'SAS_28_sumprodsTest/no28_sumprods_02.sem',
        'SAS_28_sumprodsTest/no28_sumprods_06.sem'
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
