
[[task]]
    # SAS_03_sigmaTests
    files = [
        "SAS_03_sigmaTests/no03_sigmaTest_01.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_02.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_03.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_04.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_05.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_06.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_07.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_08.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_09.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_10.sem",
        "SAS_03_sigmaTests/no03_sigmaTest_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
