
[[task]]
    # SAS_13_fibonacciTest
    files = [
        "SAS_13_fibonacciTest/no13_fibonacci_01.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_02.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_03.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_04.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_05.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_06.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_07.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_08.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_09.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_10.sem",
        "SAS_13_fibonacciTest/no13_fibonacci_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
