
[[task]]
    # SAS_26_sumsquaresTest
    files = [
        "SAS_26_sumsquaresTest/no26_sumsquares_01.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_02.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_03.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_04.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_05.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_06.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_07.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_08.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_09.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_10.sem",
        "SAS_26_sumsquaresTest/no26_sumsquares_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
