
[[task]]
    # SAS_27_prodsquaresTest
    files = [
        "SAS_27_prodsquaresTest/no27_prodsquares_01.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_02.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_03.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_04.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_05.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_06.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_07.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_08.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_09.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_10.sem",
        "SAS_27_prodsquaresTest/no27_prodsquares_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
