
[[task]]
    # SAS_28_sumprodsTest
    files = [
        "SAS_28_sumprodsTest/no28_sumprods_01.sem",
        "SAS_28_sumprodsTest/no28_sumprods_02.sem",
        "SAS_28_sumprodsTest/no28_sumprods_03.sem",
        "SAS_28_sumprodsTest/no28_sumprods_04.sem",
        "SAS_28_sumprodsTest/no28_sumprods_05.sem",
        "SAS_28_sumprodsTest/no28_sumprods_06.sem",
        "SAS_28_sumprodsTest/no28_sumprods_07.sem",
        "SAS_28_sumprodsTest/no28_sumprods_08.sem",
        "SAS_28_sumprodsTest/no28_sumprods_09.sem",
        "SAS_28_sumprodsTest/no28_sumprods_10.sem",
        "SAS_28_sumprodsTest/no28_sumprods_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
