
[[task]]
    # SAS_14_nestedSumTest
    files = [
        "SAS_14_nestedSumTest/no14_nestedsum_01.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_02.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_03.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_04.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_05.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_06.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_07.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_08.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_09.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_10.sem",
        "SAS_14_nestedSumTest/no14_nestedsum_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
