# Files for which MESSY reported SAT using any method

[[task]]
# Files for which MESSY reported SAT without bounded approx

    files = [
        'basic_1/basicTest_AddOne_01.sem',
        'basic_1/basicTest_SumByWhileLoop_01.sem',
        'basic_1/basicTest_SumWithLimitedOps_01.sem',
        'basic_bv/BVtest_AND_03.sem',
        'basic_bv/BVtest_Swap_XOR_03.sem',
        'basic_bv/BVtest_XOR_02.sem'
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"

    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "false"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"