
[[task]]
    # SAS_19_addarraysTest
    files = [
        "SAS_19_addarraysTest/no19_addarray_01.sem",
        "SAS_19_addarraysTest/no19_addarray_02.sem",
        "SAS_19_addarraysTest/no19_addarray_03.sem",
        "SAS_19_addarraysTest/no19_addarray_04.sem",
        "SAS_19_addarraysTest/no19_addarray_05.sem",
        "SAS_19_addarraysTest/no19_addarray_06.sem",
        "SAS_19_addarraysTest/no19_addarray_07.sem",
        "SAS_19_addarraysTest/no19_addarray_08.sem",
        "SAS_19_addarraysTest/no19_addarray_09.sem",
        "SAS_19_addarraysTest/no19_addarray_10.sem",
        "SAS_19_addarraysTest/no19_addarray_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
