
[[task]]
    # SAS_23_maxTest
    files = [
        "SAS_23_maxTest/no23_max_01.sem",
        "SAS_23_maxTest/no23_max_02.sem",
        "SAS_23_maxTest/no23_max_03.sem",
        "SAS_23_maxTest/no23_max_04.sem",
        "SAS_23_maxTest/no23_max_05.sem",
        "SAS_23_maxTest/no23_max_06.sem",
        "SAS_23_maxTest/no23_max_07.sem",
        "SAS_23_maxTest/no23_max_08.sem",
        "SAS_23_maxTest/no23_max_09.sem",
        "SAS_23_maxTest/no23_max_10.sem",
        "SAS_23_maxTest/no23_max_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
