
[[task]]
    # SAS_24_minTest
    files = [
        "SAS_24_minTest/no24_min_01.sem",
        "SAS_24_minTest/no24_min_02.sem",
        "SAS_24_minTest/no24_min_03.sem",
        "SAS_24_minTest/no24_min_04.sem",
        "SAS_24_minTest/no24_min_05.sem",
        "SAS_24_minTest/no24_min_06.sem",
        "SAS_24_minTest/no24_min_07.sem",
        "SAS_24_minTest/no24_min_08.sem",
        "SAS_24_minTest/no24_min_09.sem",
        "SAS_24_minTest/no24_min_10.sem",
        "SAS_24_minTest/no24_min_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
