
[[task]]
    # SAS_07_suma2nTest
    files = [
        "SAS_07_suma2nTest/no07_suma2n_01.sem",
        "SAS_07_suma2nTest/no07_suma2n_02.sem",
        "SAS_07_suma2nTest/no07_suma2n_03.sem",
        "SAS_07_suma2nTest/no07_suma2n_04.sem",
        "SAS_07_suma2nTest/no07_suma2n_05.sem",
        "SAS_07_suma2nTest/no07_suma2n_06.sem",
        "SAS_07_suma2nTest/no07_suma2n_07.sem",
        "SAS_07_suma2nTest/no07_suma2n_08.sem",
        "SAS_07_suma2nTest/no07_suma2n_09.sem",
        "SAS_07_suma2nTest/no07_suma2n_10.sem",
        "SAS_07_suma2nTest/no07_suma2n_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
