
[[task]]
    # SAS_22_quartarrayTest
    files = [
        "SAS_22_quartarrayTest/no22_quartarray_01.sem",
        "SAS_22_quartarrayTest/no22_quartarray_02.sem",
        "SAS_22_quartarrayTest/no22_quartarray_03.sem",
        "SAS_22_quartarrayTest/no22_quartarray_04.sem",
        "SAS_22_quartarrayTest/no22_quartarray_05.sem",
        "SAS_22_quartarrayTest/no22_quartarray_06.sem",
        "SAS_22_quartarrayTest/no22_quartarray_07.sem",
        "SAS_22_quartarrayTest/no22_quartarray_08.sem",
        "SAS_22_quartarrayTest/no22_quartarray_09.sem",
        "SAS_22_quartarrayTest/no22_quartarray_10.sem",
        "SAS_22_quartarrayTest/no22_quartarray_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
