
[[task]]
    # SAS_04_sigmaSquareTests
    files = [
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_01.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_02.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_03.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_04.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_05.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_06.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_07.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_08.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_09.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_10.sem",
        "SAS_04_sigmaSquareTests/no04_sigmaSquare_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
