
[[task]]
    # SAS_18_arrayprodTest
    files = [
        "SAS_18_arrayprodTest/no18_arrayprod_01.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_02.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_03.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_04.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_05.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_06.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_07.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_08.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_09.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_10.sem",
        "SAS_18_arrayprodTest/no18_arrayprod_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "false"
            interpreter_max_depth = 100
            halt_on_parse_error = "true"
