
[[task]]
    # SAS_01_factorialTests
    files = [
        "SAS_01_factorialTests/no01_factorialTest_01.sem",
        "SAS_01_factorialTests/no01_factorialTest_02.sem",
        "SAS_01_factorialTests/no01_factorialTest_03.sem",
        "SAS_01_factorialTests/no01_factorialTest_04.sem",
        "SAS_01_factorialTests/no01_factorialTest_05.sem",
        "SAS_01_factorialTests/no01_factorialTest_06.sem",
        "SAS_01_factorialTests/no01_factorialTest_07.sem",
        "SAS_01_factorialTests/no01_factorialTest_08.sem",
        "SAS_01_factorialTests/no01_factorialTest_09.sem",
        "SAS_01_factorialTests/no01_factorialTest_10.sem",
        "SAS_01_factorialTests/no01_factorialTest_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
