
[[task]]
    # SAS_21_cubearrayTest
    files = [
        "SAS_21_cubearrayTest/no21_cubearray_01.sem",
        "SAS_21_cubearrayTest/no21_cubearray_02.sem",
        "SAS_21_cubearrayTest/no21_cubearray_03.sem",
        "SAS_21_cubearrayTest/no21_cubearray_04.sem",
        "SAS_21_cubearrayTest/no21_cubearray_05.sem",
        "SAS_21_cubearrayTest/no21_cubearray_06.sem",
        "SAS_21_cubearrayTest/no21_cubearray_07.sem",
        "SAS_21_cubearrayTest/no21_cubearray_08.sem",
        "SAS_21_cubearrayTest/no21_cubearray_09.sem",
        "SAS_21_cubearrayTest/no21_cubearray_10.sem",
        "SAS_21_cubearrayTest/no21_cubearray_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
