
[[task]]
    # SAS_25_addoneTest
    files = [
        "SAS_25_addoneTest/no25_addone_01.sem",
        "SAS_25_addoneTest/no25_addone_02.sem",
        "SAS_25_addoneTest/no25_addone_03.sem",
        "SAS_25_addoneTest/no25_addone_04.sem",
        "SAS_25_addoneTest/no25_addone_05.sem",
        "SAS_25_addoneTest/no25_addone_06.sem",
        "SAS_25_addoneTest/no25_addone_07.sem",
        "SAS_25_addoneTest/no25_addone_08.sem",
        "SAS_25_addoneTest/no25_addone_09.sem",
        "SAS_25_addoneTest/no25_addone_10.sem",
        "SAS_25_addoneTest/no25_addone_11.sem",
    ]
    
    # temp field to set background theory
    lib = "lia"
    
    # array of solver configurations to apply for each problem
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
            use_observational_equivalence_reduction = "true"
            interpreter_max_depth = 1000
            halt_on_parse_error = "true"
