
[[task]]
    files = [
        "./magic/linear/GCPE_01.sem",
        "./magic/linear/GCPE_02.sem",
        "./magic/linear/GCPE_03.sem",
        "./magic/linear/GCPE_04.sem",
        "./magic/linear/GCPE_05.sem",
        "./magic/linear/GCPE_06.sem",
        "./magic/linear/GCPE_07.sem",
        "./magic/linear/GCPE_08.sem",
        "./magic/linear/GCPE_09.sem",
        "./magic/linear/GCPE_10.sem",
        "./magic/linear/GCPE_11.sem",
        "./magic/linear/GCPE_12.sem",
        "./magic/linear/GCPE_13.sem",
        "./magic/linear/GCPE_14.sem",
        "./magic/linear/GCPE_15.sem",
        "./magic/linear/GCPE_16.sem",
        "./magic/linear/GCPE_17.sem",
        "./magic/linear/GCPE_18.sem",
        "./magic/linear/GCPE_19.sem",
        "./magic/linear/GCPE_20.sem",
        "./magic/linear/GCPE_21.sem",
        "./magic/linear/GCPE_22.sem",
        "./magic/linear/GCPE_23.sem",
        "./magic/linear/GCPE_24.sem",
        "./magic/linear/GCPE_25.sem",
    ]

    lib = "regex_bmat" 
    
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"


[[task]]
    files = [
        "./magic/logarithmic/GCPE_01.sem",
        "./magic/logarithmic/GCPE_02.sem",
        "./magic/logarithmic/GCPE_03.sem",
        "./magic/logarithmic/GCPE_04.sem",
        "./magic/logarithmic/GCPE_05.sem",
        "./magic/logarithmic/GCPE_06.sem",
        "./magic/logarithmic/GCPE_07.sem",
        "./magic/logarithmic/GCPE_08.sem",
        "./magic/logarithmic/GCPE_09.sem",
        "./magic/logarithmic/GCPE_10.sem",
        "./magic/logarithmic/GCPE_11.sem",
        "./magic/logarithmic/GCPE_12.sem",
        "./magic/logarithmic/GCPE_13.sem",
        "./magic/logarithmic/GCPE_14.sem",
        "./magic/logarithmic/GCPE_15.sem",
        "./magic/logarithmic/GCPE_16.sem",
        "./magic/logarithmic/GCPE_17.sem",
        "./magic/logarithmic/GCPE_18.sem",
        "./magic/logarithmic/GCPE_19.sem",
        "./magic/logarithmic/GCPE_20.sem",
        "./magic/logarithmic/GCPE_21.sem",
        "./magic/logarithmic/GCPE_22.sem",
        "./magic/logarithmic/GCPE_23.sem",
        "./magic/logarithmic/GCPE_24.sem",
        "./magic/logarithmic/GCPE_25.sem",
    ]

    lib = "regex_bmat" 
    
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"

[[task]]
    files = [
        "./fixed-length/linear/GCPE_01.sem",
        "./fixed-length/linear/GCPE_02.sem",
        "./fixed-length/linear/GCPE_03.sem",
        "./fixed-length/linear/GCPE_04.sem",
        "./fixed-length/linear/GCPE_05.sem",
        "./fixed-length/linear/GCPE_06.sem",
        "./fixed-length/linear/GCPE_07.sem",
        "./fixed-length/linear/GCPE_08.sem",
        "./fixed-length/linear/GCPE_09.sem",
        "./fixed-length/linear/GCPE_10.sem",
        "./fixed-length/linear/GCPE_11.sem",
        "./fixed-length/linear/GCPE_12.sem",
        "./fixed-length/linear/GCPE_13.sem",
        "./fixed-length/linear/GCPE_14.sem",
        "./fixed-length/linear/GCPE_15.sem",
        "./fixed-length/linear/GCPE_16.sem",
        "./fixed-length/linear/GCPE_17.sem",
        "./fixed-length/linear/GCPE_18.sem",
        "./fixed-length/linear/GCPE_19.sem",
        "./fixed-length/linear/GCPE_20.sem",
        "./fixed-length/linear/GCPE_21.sem",
        "./fixed-length/linear/GCPE_22.sem",
        "./fixed-length/linear/GCPE_23.sem",
        "./fixed-length/linear/GCPE_24.sem",
        "./fixed-length/linear/GCPE_25.sem",
    ]

    lib = "lia" 
    
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"
[[task]]
    files = [
        "./fixed-length/logarithmic/GCPE_01.sem",
        "./fixed-length/logarithmic/GCPE_02.sem",
        "./fixed-length/logarithmic/GCPE_03.sem",
        "./fixed-length/logarithmic/GCPE_04.sem",
        "./fixed-length/logarithmic/GCPE_05.sem",
        "./fixed-length/logarithmic/GCPE_06.sem",
        "./fixed-length/logarithmic/GCPE_07.sem",
        "./fixed-length/logarithmic/GCPE_08.sem",
        "./fixed-length/logarithmic/GCPE_09.sem",
        "./fixed-length/logarithmic/GCPE_10.sem",
        "./fixed-length/logarithmic/GCPE_11.sem",
        "./fixed-length/logarithmic/GCPE_12.sem",
        "./fixed-length/logarithmic/GCPE_13.sem",
        "./fixed-length/logarithmic/GCPE_14.sem",
        "./fixed-length/logarithmic/GCPE_15.sem",
        "./fixed-length/logarithmic/GCPE_16.sem",
        "./fixed-length/logarithmic/GCPE_17.sem",
        "./fixed-length/logarithmic/GCPE_18.sem",
        "./fixed-length/logarithmic/GCPE_19.sem",
        "./fixed-length/logarithmic/GCPE_20.sem",
        "./fixed-length/logarithmic/GCPE_21.sem",
        "./fixed-length/logarithmic/GCPE_22.sem",
        "./fixed-length/logarithmic/GCPE_23.sem",
        "./fixed-length/logarithmic/GCPE_24.sem",
        "./fixed-length/logarithmic/GCPE_25.sem",
    ]

    lib = "lia" 
    
    [[task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [task.solver.params]
            cost_function = "size"