
[[synth_task]]
    files = [
        "./fixed-length/logarithmic/GCPE_01.sem",
        "./fixed-length/logarithmic/GCPE_02.sem",
        "./fixed-length/logarithmic/GCPE_03.sem",
        "./fixed-length/logarithmic/GCPE_04.sem",
        "./fixed-length/logarithmic/GCPE_05.sem",
        "./fixed-length/logarithmic/GCPE_06.sem",
        "./fixed-length/logarithmic/GCPE_07.sem",
        "./fixed-length/logarithmic/GCPE_08.sem",
        "./fixed-length/logarithmic/GCPE_09.sem",
        "./fixed-length/logarithmic/GCPE_10.sem",
        "./fixed-length/logarithmic/GCPE_11.sem",
        "./fixed-length/logarithmic/GCPE_12.sem",
        "./fixed-length/logarithmic/GCPE_13.sem",
        "./fixed-length/logarithmic/GCPE_14.sem",
        "./fixed-length/logarithmic/GCPE_15.sem",
        "./fixed-length/logarithmic/GCPE_16.sem",
        "./fixed-length/logarithmic/GCPE_17.sem",
        "./fixed-length/logarithmic/GCPE_18.sem",
        "./fixed-length/logarithmic/GCPE_19.sem",
        "./fixed-length/logarithmic/GCPE_20.sem",
        "./fixed-length/logarithmic/GCPE_21.sem",
        "./fixed-length/logarithmic/GCPE_22.sem",
        "./fixed-length/logarithmic/GCPE_23.sem",
        "./fixed-length/logarithmic/GCPE_24.sem",
        "./fixed-length/logarithmic/GCPE_25.sem",
    ]
    
    [[synth_task.solver]]
        method = "bottom_up"
        timeout = 600 # in seconds
        
        [synth_task.solver.params]
            cost_function = "size"