name: Parse Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  # Don't make dotnet so needy
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Update Environment
      run: |
        echo "DOTNET_ROOT=${HOME}/.dotnet" >> $GITHUB_ENV
        echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
        
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install Parser
      run: dotnet tool install --global Semgus.Parser.Tool --version 2.0.0-alpha4 # Changeme

    - name: Test
      run: semgus-parser --help

